### ISSUE TITLE
구글 스토리지 (GCS) 관련 설정하기

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-backend#61]
(1) json 파일 저장
json 파일의 경우 공개적으로 공유하면 안되니 따로 보내드리겠습니다! 
해당 파일을 `src/main/resources/navada-village-377308-588aac17f6ed.json` 경로에 저장해주세요

(2) 환경 변수 설정
각자 로컬에도 환경변수 설정이 필요한 것 같습니다.
`GOOGLE_APPLICATION_CREDENTIAL = {json파일경로}` 로 환경변수 등록

(3) application.yml 수정
```yml
spring:
  profiles:
    active: local

  #gcp storage
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:navada-village-377308-588aac17f6ed.json
        host: "https://storage.googleapis.com/"
        bucket: "navadavillage-bucket"
```
위와 같이 수정해주세요 (local.yml 만 gitignore에 두고 이 파일은 공통적인것만 모아서 제외시켜도 될 것 같네요)

(3) build.gradle 리빌드! 
추가된 라이브러리들이 있어서 리로드 해주세요

이렇게 해보시고 이미지 업로드는 우선 Postman 으로 테스트 부탁드립니다! (상품 등록 api 수정해놓았어요)
일단 storage에 잘 저장되는것까지 확인했는데, 관련해서 다른 문제들 발생하면 말씀해주세요

모바일 앱에서 네트워크로 바로 받아오는것까지 작성하려고했는데, 생각해보니까 갤러리에서 사진 가져오는 부분까지 구현이 필요하더라구요,, 이 부분은 다음 스프린트때 진행해야 할 것 같습니다!
